[project]
name = "fastapi-oauth2-server"
version = "0.1.0"
description = "Example FastAPI OAuth 2 Server w/ Authlib."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "authlib",
    "fastapi[standard]",
    "uvicorn[standard]",
    "starlette[full]",
    "pydantic-settings",
    "pyjwt[crypto]",
    "anyio>=4",
    "SQLAlchemy>=2",
]

[dependency-groups]
dev = ["prek", "ruff", "ty", "pytest", "httpx2"]

[tool.pytest.ini_options]
pythonpath = ["."]
anyio_mode = "auto"

[tool.fastapi]
entrypoint = "fastapi_oauth2.asgi:create_app"

[tool.ty.environment]
python-platform = "all"
